[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = huge_app.csv
build_src_filter =
  +<common/>
  +<radio/>
upload_port = /dev/ttyUSB0
upload_speed = 115200
monitor_speed = 115200
build_flags =
  -I src/common
  -D GOPRO_LOCAL_WIFI_SSID=\"razor\"
  -D GOPRO_LOCAL_WIFI_PASSWORD=\"8323351618\"
  -D GOPRO_CAMERA_NAME_FILTER=\"GoPro,MISSION,GP\"
  -D GOPRO_AUTO_START=1

[env:esp32s3_radio]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.partitions = huge_app.csv
build_src_filter =
  +<common/>
  +<radio/>
monitor_speed = 115200
build_flags =
  -I src/common
  -D GOPRO_LOCAL_WIFI_SSID=\"razor\"
  -D GOPRO_LOCAL_WIFI_PASSWORD=\"8323351618\"
  -D GOPRO_CAMERA_NAME_FILTER=\"GoPro,MISSION,GP\"
  -D GOPRO_AUTO_START=0
  -D GOPRO_LINK_RX_PIN=16
  -D GOPRO_LINK_TX_PIN=17

[env:ui_esp32dev_sim]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = huge_app.csv
build_src_filter =
  +<common/>
  +<ui/>
monitor_speed = 115200
build_flags =
  -I src/common
  -D GOPRO_UI_LINK_RX_PIN=16
  -D GOPRO_UI_LINK_TX_PIN=17

[env:esp32p4_ui]
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32-p4_r3-evboard
framework = arduino
build_src_filter =
  +<common/>
  +<ui/>
monitor_speed = 115200
build_flags =
  -I src/common
  -D GOPRO_UI_LINK_RX_PIN=16
  -D GOPRO_UI_LINK_TX_PIN=17
