"""Package explicitly selected, print-oriented binary STLs on 250 mm plates.

Uses 3MF core meshes plus the Bambu Studio / OrcaSlicer plate convention.
No printer, material or slicing profile is imposed. Standard 3MF readers can
import the meshes, but readers without plate support must arrange them.
"""
from pathlib import Path
import json
import math
import struct
import tempfile
import xml.etree.ElementTree as ET
import zipfile

CORE = 'http://schemas.microsoft.com/3dmanufacturing/core/2015/02'
REL = 'http://schemas.openxmlformats.org/package/2006/relationships'
CONTENT = 'http://schemas.openxmlformats.org/package/2006/content-types'
MODEL_REL = 'http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel'


def tag(name):
    return f'{{{CORE}}}{name}'


def stl_payload(path):
    data = Path(path).read_bytes()
    if len(data) < 84:
        raise ValueError(f'Incomplete binary STL: {path}')
    count = struct.unpack_from('<I', data, 80)[0]
    if not count or len(data) != 84 + count * 50:
        raise ValueError(f'Invalid binary STL: {path}')
    vertices, faces, lookup = [], [], {}
    for record in struct.iter_unpack('<12fH', data[84:]):
        face = []
        for offset in (3, 6, 9):
            point = tuple(record[offset:offset + 3])
            if not all(math.isfinite(value) for value in point):
                raise ValueError(f'Nonfinite STL vertex: {path}')
            if point not in lookup:
                lookup[point] = len(vertices)
                vertices.append(point)
            face.append(lookup[point])
        if len(set(face)) != 3:
            raise ValueError(f'Degenerate STL triangle: {path}')
        faces.append(tuple(face))
    return vertices, faces


def metadata(node, key, value):
    ET.SubElement(node, 'metadata', {'key': key, 'value': str(value)})


def xml_bytes(node):
    return ET.tostring(node, encoding='utf-8', xml_declaration=True)


def export_print_project(path, stl_paths, bed_size=250.0):
    """Export exactly this run's printable parts, one centered part per plate."""
    path = Path(path)
    stl_paths = [Path(item) for item in stl_paths]
    if not stl_paths or len({p.name for p in stl_paths}) != len(stl_paths):
        raise ValueError('3MF requires a nonempty, unique printable part list')
    if not math.isfinite(bed_size) or bed_size <= 0:
        raise ValueError('3MF bed size must be finite and positive')
    ET.register_namespace('', CORE)
    model = ET.Element(tag('model'), {'unit': 'millimeter', '{http://www.w3.org/XML/1998/namespace}lang': 'en-US'})
    # Bambu gates project-setting import on this compatibility marker.
    ET.SubElement(model, tag('metadata'), {'name': 'Application'}).text = 'BambuStudio-02.05.01.52'
    ET.SubElement(model, tag('metadata'), {'name': 'Description'}).text = 'Generated by HockeyMON model tools; select printer and material before slicing.'
    ET.SubElement(model, tag('metadata'), {'name': 'BambuStudio:3mfVersion'}).text = '1'
    ET.SubElement(model, tag('metadata'), {'name': 'Title'}).text = 'HockeyMON camera case printable parts'
    resources = ET.SubElement(model, tag('resources'))
    build = ET.SubElement(model, tag('build'))
    settings = ET.Element('config')
    columns = math.ceil(math.sqrt(len(stl_paths)))
    manifest = []
    for index, source in enumerate(stl_paths):
        object_id = str(index + 1)
        vertices, faces = stl_payload(source)
        bounds = [(min(v[a] for v in vertices), max(v[a] for v in vertices)) for a in range(3)]
        spans = [high-low for low, high in bounds]
        if max(spans[:2]) > bed_size + 0.001:
            raise ValueError(f'{source.name} exceeds {bed_size:g} mm plate: {spans}')
        if abs(bounds[2][0]) > 0.001:
            raise ValueError(f'{source.name} must rest on Z=0 before packaging')
        name = source.stem.removeprefix('hockeymom_cam_case_').replace('_', ' ')
        obj = ET.SubElement(resources, tag('object'), {'id': object_id, 'type': 'model', 'name': name})
        mesh = ET.SubElement(obj, tag('mesh'))
        vertex_node = ET.SubElement(mesh, tag('vertices'))
        for vertex in vertices:
            ET.SubElement(vertex_node, tag('vertex'), {axis: format(value, '.9g') for axis, value in zip(('x','y','z'), vertex)})
        triangle_node = ET.SubElement(mesh, tag('triangles'))
        for face in faces:
            ET.SubElement(triangle_node, tag('triangle'), {key: str(value) for key, value in zip(('v1','v2','v3'), face)})
        origin = ((index % columns)*bed_size*1.2, -(index//columns)*bed_size*1.2)
        x, y = [origin[a]+bed_size/2-sum(bounds[a])/2 for a in range(2)]
        ET.SubElement(build, tag('item'), {'objectid': object_id, 'printable': '1', 'transform': f'1 0 0 0 1 0 0 0 1 {x:.9g} {y:.9g} 0'})
        config_obj = ET.SubElement(settings, 'object', {'id': object_id})
        metadata(config_obj, 'name', name)
        metadata(config_obj, 'extruder', '1')
        part = ET.SubElement(config_obj, 'part', {'id': object_id, 'subtype': 'normal_part'})
        metadata(part, 'name', name)
        metadata(part, 'source_file', source.name)
        metadata(part, 'extruder', '1')
        plate = ET.SubElement(settings, 'plate')
        metadata(plate, 'plater_id', index+1)
        metadata(plate, 'plater_name', name)
        metadata(plate, 'locked', 'false')
        instance = ET.SubElement(plate, 'model_instance')
        for key, value in (('object_id',object_id),('instance_id',0),('identify_id',index+1)):
            metadata(instance, key, value)
        manifest.append({'source': source.name, 'object_id': index+1, 'plate': index+1, 'plate_origin': origin, 'dimensions_mm': spans})
    ET.SubElement(settings, 'assemble')
    types = ET.Element('Types', {'xmlns': CONTENT})
    for extension, content_type in (('rels','application/vnd.openxmlformats-package.relationships+xml'),('model','application/vnd.ms-package.3dmanufacturing-3dmodel+xml'),('config','application/octet-stream'),('json','application/json')):
        ET.SubElement(types, 'Default', {'Extension': extension, 'ContentType': content_type})
    relationships = ET.Element('Relationships', {'xmlns': REL})
    ET.SubElement(relationships, 'Relationship', {'Target':'/3D/3dmodel.model', 'Id':'rel-1', 'Type':MODEL_REL})
    project_settings = {
        # One process slot, one unassigned filament slot, and one printer slot.
        # Bambu's preset conversion indexes these arrays even without presets.
        'different_settings_to_system': [''] * 3, 'inherits_group': [''] * 3,
        'filament_settings_id': [''], 'filament_ids': [''],
        'filament_colour': ['#225978'], 'filament_type': [''],
        'filament_is_support': ['0'], 'flush_multiplier': ['1'],
        'flush_volumes_matrix': ['0'],
        'print_settings_id': '', 'printer_settings_id': '',
        'nozzle_diameter': ['0.4'], 'printable_height': '250',
        'printable_area': ['0x0',f'{bed_size:g}x0',f'{bed_size:g}x{bed_size:g}',f'0x{bed_size:g}'], 'bed_exclude_area': []}
    members = {'[Content_Types].xml': xml_bytes(types), '_rels/.rels': xml_bytes(relationships), '3D/3dmodel.model': xml_bytes(model), 'Metadata/model_settings.config': xml_bytes(settings), 'Metadata/project_settings.config': json.dumps(project_settings).encode(), 'Metadata/print_manifest.json': json.dumps({'bed_size_mm': bed_size, 'parts': manifest}, indent=2).encode()}
    with tempfile.NamedTemporaryFile(dir=path.parent, prefix='.'+path.name, delete=False) as stream:
        temporary = Path(stream.name)
    try:
        with zipfile.ZipFile(temporary, 'w', compression=zipfile.ZIP_DEFLATED) as archive:
            for name, data in members.items():
                info = zipfile.ZipInfo(name, date_time=(1980,1,1,0,0,0))
                info.compress_type = zipfile.ZIP_DEFLATED
                archive.writestr(info, data)
        validate_print_project(temporary, stl_paths)
        temporary.replace(path)
    finally:
        temporary.unlink(missing_ok=True)
    print(f'EXPORTED_3MF {path} parts={len(stl_paths)} plates={len(stl_paths)} bed={bed_size:g}mm')
    return path


def validate_print_project(path, stl_paths):
    """Read back package, compare each STL mesh and check placed bed bounds."""
    with zipfile.ZipFile(path) as archive:
        if archive.testzip():
            raise ValueError('Corrupt 3MF archive')
        model = ET.fromstring(archive.read('3D/3dmodel.model'))
        manifest = json.loads(archive.read('Metadata/print_manifest.json'))
        config = ET.fromstring(archive.read('Metadata/model_settings.config'))
    assert model.get('unit') == 'millimeter'
    objects = model.find(tag('resources')).findall(tag('object'))
    items = model.find(tag('build')).findall(tag('item'))
    plates = config.findall('plate')
    assert len(objects) == len(items) == len(plates) == len(stl_paths) == len(manifest['parts'])
    for index, (obj, item, plate, source, record) in enumerate(zip(objects, items, plates, stl_paths, manifest['parts']), 1):
        assert obj.get('id') == item.get('objectid') == str(index)
        values = {m.get('key'): m.get('value') for m in plate.find('model_instance').findall('metadata')}
        assert values['object_id'] == str(index) and values['instance_id'] == '0'
        assert record['source'] == Path(source).name
        expected_vertices, expected_faces = stl_payload(source)
        mesh = obj.find(tag('mesh'))
        vertices = [tuple(float(v.get(a)) for a in ('x','y','z')) for v in mesh.find(tag('vertices'))]
        faces = [tuple(int(f.get(a)) for a in ('v1','v2','v3')) for f in mesh.find(tag('triangles'))]
        assert faces == expected_faces and len(vertices) == len(expected_vertices)
        assert all(abs(a-b)<0.000001 for v,w in zip(vertices,expected_vertices) for a,b in zip(v,w))
        transform = list(map(float, item.get('transform').split()))
        assert transform[:9] == [1,0,0,0,1,0,0,0,1] and transform[11] == 0
        for axis in range(2):
            low = min(v[axis] for v in vertices)+transform[9+axis]-record['plate_origin'][axis]
            high = max(v[axis] for v in vertices)+transform[9+axis]-record['plate_origin'][axis]
            assert low >= -0.001 and high <= manifest['bed_size_mm']+0.001
        assert abs(min(v[2] for v in vertices)) < 0.001
